spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:hodolog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  jpa:
    defer-datasource-initialization: true

  sql:
    init:
      mode: always