spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:hodolog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        max-page-size: 2000
        one-indexed-parameters: true
        default-page-size: 5

hodolman:
  jwt-key: IT+oSV+G8YN8F9yqB3K5T3aIRnxZdYj2AS+p8e9DfpQ=